POST http://localhost:8080/App/rest/auth/user/login
Content-Type: application/json

{
  "email": "kristel",
  "password": "Kristel123"
}

###
POST http://localhost:8080/App/rest/auth/guest/login
Content-Type: application/json

{
  "code": "b123b",
  "surname": "Mirkhan"
}

###
POST http://localhost:8080/App/rest/auth/user/login
Content-Type: application/json

{
  "email": "kristel@gmail.com",
  "password": "Kristel123"
}

####
POST http://localhost:8080/App/rest/auth/user/logout

###
DELETE http://localhost:8080/App/rest/user/delete/BX001
